spring:
  application:
    name: sfg-brewery-gateway
  cloud:
    gateway:
      routes:
        - id: beer-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/v1/beer*,/api/v1/beer/*,/api/v1/upcbeer*,/api/v1/upcbeer/*
        - id: beer-order-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/v1/customers*,/api/v1/customers/**
        - id: beer-inventory-service
          uri: http://localhost:8083
          predicates:
            - Path=/api/v1/beer/*/inventory
server:
  port: 9090
logging:
  level:
    guru.sfg.brewery.gateway: DEBUG
    reactor.netty.http.client: DEBUG