version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.10.0
    ports:
      - 9200:9200
    environment:
      discovery.type: single-node
  kibana:
    image: docker.elastic.co/kibana/kibana:7.10.0
    ports:
      - 5601:5601
    restart: on-failure
    depends_on:
      - elasticsearch
  filebeat:
    image: docker.elastic.co/beats/filebeat:7.10.0
    command: filebeat -e -strict.perms=false
    volumes:
      - ./filebeat/filebeat.docker.yml:/usr/share/filebeat/filebeat.yml:ro # Configuration file, ro: readonly
      - /var/lib/docker/containers:/var/lib/docker/containers:ro           # Docker logs, ro: readonly
      - /var/run/docker.sock:/var/run/docker.sock:ro                       # Additional information about containers, ro: readonly
    user: root                                                             # Allow access to log files and docker.sock
    restart: on-failure
  jms:
    image: vromero/activemq-artemis
    ports:
      - 8161:8161
      - 61616:61616
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  eureka:
    image: yulcloud/mssc-brewery-eureka
    ports:
      - 8761:8761
  config:
    image: yulcloud/mssc-brewery-config
    ports:
      - 8888:8888
    depends_on:
      - eureka
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      # EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://yulikexuan:password@eureka:8761/eureka/
  inventory-service:
    image: yulcloud/mssc-beer-inventory-service
    ports:
      - 8083:8083
    depends_on:
      - eureka
      - config
      - jms
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_ARTEMIS_HOST: jms
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
      # SPRING-DATASOURCE-URL: jdbc:postgresql://host.docker.internal:5432/beer_inventory_service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    restart: on-failure
    # A label is a key-value pair, stored as a string
    # You can specify multiple labels for an object, but each key-value pair
    # must be unique within an object
    # If the same key is given multiple values, the most-recently-written value
    # overwrites all previous values
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  inventory-failover:
    image: yulcloud/mssc-inventory-failover
    ports:
      - 8084:8084
    depends_on:
      - eureka
      - config
      - jms
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_ARTEMIS_HOST: jms
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure
  beer-service:
    image: yulcloud/mssc-beer-service
    ports:
      - 8081:8081
    depends_on:
      - eureka
      - config
      - jms
      - inventory-service
      - inventory-failover
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_ARTEMIS_HOST: jms
      SFG_BREWERY_BEER-INVENTORY-SERVICE-HOST: http://inventory-service:8083
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  order-service:
    image: yulcloud/mssc-beer-order-service
    ports:
      - 8082:8082
    depends_on:
      - eureka
      - config
      - jms
      - inventory-service
      - inventory-failover
      - beer-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
      SPRING_ARTEMIS_HOST: jms
      SFG_BREWERY_BEER-INVENTORY-SERVICE-HOST: http://inventory-service:8083
      SFG_BREWERY_BEER-SERVICE-HOST: http://beer-service:8081
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"
  # gateway does not use config server
  gateway:
    image: yulcloud/mssc-brewery-gateway
    ports:
      - 9090:9090
    depends_on:
      - eureka
      - config
      - inventory-service
      - beer-service
      - order-service
      - inventory-failover
    environment:
      SPRING_PROFILES_ACTIVE: docker
      EUREKA_INSTANCE_PREFER_IP_ADDRESS: 'true'
    restart: on-failure
    labels:
      collect_logs_with_filebeat: "true"
      decode_log_event_to_json_object: "true"