server:
  port: 8081
# Config H2 Console
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate.format_sql: true
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password
    initialization-mode: EMBEDDED
  h2:
    console:
      enabled: true
# Cache Setup
  cache:
    jcache:
      config: classpath:ehcache.xml
  output:
    ansi:
      enabled: detect
# Service Properties
sfg:
  brewery:
    beer-inventory-service-host: http://localhost:8083
#logging:
logging:
  level:
    # guru: debug
    org.hibernate:
        sql: DEBUG
        type: TRACE