spring:
  jpa:
    database: postgresql
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQL10Dialect
  datasource:
    initialization-mode: always
    url: jdbc:postgresql://localhost:5432/beer_order_service?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    driver-class-name: org.postgresql.Driver
    username: beer_order_service_guru
    password: password
