#logging:
#  level:
#    guru: debug
server:
  port: 8082
# Config H2 Console
spring:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb;MODE=PostgreSQL
    driver-class-name: org.h2.Driver
    username: sa
    password: password
  h2:
    console:
      enabled: true
sfg:
  brewery:
    beer-service-host: http://localhost:8081